
spring:
  profiles:
    active: dev
  application:
    name: alarm-server_web
  session:
    store-type: redis
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2

server:
  name: ALARM_SERVER_WEB_TEST #\u670D\u52A1\u7F16\u7801
  version: V1.0.0 #\u670D\u52A1\u7248\u672C,\u53EF\u4EE5\u6269\u5C55\u4E3A * app
  port: 19000 #\u670D\u52A1\u5360\u7528web\u7AEF\u53E3 \u5360\u7528\u62E6\u622A{/mqtt/*,/register*}
  title: 告警服务
#  serverUri: /home #首页名
  pageRoute: proxy_alarm
  routeMark: proxy_alarm

#jarResources:
#  path: ./jarResources #\u53EF\u9009\u914D\u7F6E jar\u5305\u548CjarRes.yml\u8D44\u6E90\u914D\u7F6E\u6587\u4EF6\u5B58\u653E\u8DEF\u5F84 \u9ED8\u8BA4\u4E3A./jarResources
register:
  scanBasePackage: com.kongtrolink.framework.mqtt #\u9ED8\u8BA4\u914D\u7F6Ecom.kongtrolink.framework \u5982\u679C\u9879\u76EE\u7684\u5305\u540D\u4E0D\u4E00\u81F4\u9700\u8981\u624B\u52A8\u914D\u7F6E
#  url: zookeeper://172.16.5.26:2181,172.16.5.26:2182,172.16.5.26:2183 #\u5F00\u53D1\u6001\u7684\u670D\u52A1\u548C\u4E91\u7BA1\u670D\u52A1\u914D\u7F6E\uFF0C\u5F00\u53D1\u6001\u670D\u52A1\u53EF\u4EE5\u4E0D\u4F9D\u8D56\u4E91\u7BA1\u8FDB\u884C\u90E8\u5206\u529F\u80FD\u670D\u52A1\u7684\u5F00\u53D1
mqtt:
  username: root #\u53EF\u9009\u914D\u7F6E mqtt\u914D\u7F6E\u76F8\u5173
  password: 123456 #\u53EF\u9009\u914D\u7F6E mqtt\u914D\u7F6E\u76F8\u5173
#  url: tcp://172.16.5.26:1883 #\u63A8\u9001\u4FE1\u606F\u7684\u8FDE\u63A5\u5730\u5740\uFF0C\u5982\u679C\u6709\u591A\u4E2A\uFF0C\u7528\u9017\u53F7\u9694\u5F00\uFF0C\u5982\uFF1Atcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  url: tcp://172.16.5.62:1883 #\u63A8\u9001\u4FE1\u606F\u7684\u8FDE\u63A5\u5730\u5740\uFF0C\u5982\u679C\u6709\u591A\u4E2A\uFF0C\u7528\u9017\u53F7\u9694\u5F00\uFF0C\u5982\uFF1Atcp://127.0.0.1:61613,tcp://192.168.1.61:61613

mongodb:
#  uri: mongodb://172.16.6.9:27017/alarm_server
  uri: mongodb://172.16.5.61:27017/alarm_server

unique:
  service:
    levelHandle:
      defaulg: serverCode1.operaCode1
      opera2: serverCode2.operaCode2

#默认投递动作
sender:
  serverVersion: ALARM_SERVER_SENDER_DEFAULT_1.0.0
  operaCode: handleSender

#默认sms短信相关配置
sms:
  enable: ture
  url: http://sendcloud.sohu.com/smsapi/send
  urlN: http://sendcloud.sohu.com/smsapi/sendn
  sms_user: KONGTROLINK
  sms_key: BrTgrtdfTIkqdTLbp0mzxu7wc7FRHErV
  alarm:
    reportTemplateId: 1144
  # 告警消除提示模板 id
    recoverTemplateId: 2573

##默认相关配置
email:
  url: http://api.sendcloud.net/apiv2/mail/sendtemplate
  api_user: Kongtrolink_test_Fnwqd9
  api_key: h3AGMVPe7ir8siUw
  from_address: zhouj@kongtrolink.com
  from_name: yytd
  alarm:
      reportTemplateId: power_alarm_templetId
  #消除告警邮件模板
      recoverTemplateId: power_alarm_clearId

#默认APP推送相关配置
jpush:
  appKey: 6d050a833fa17919b719d02c
#jpush.masterSecret.yiyi=185e690a9858c0b580e7f0c0
  masterSecret:  59dbddde70bf61d9e03b2c21
  # JPush 配置证书版本（开发为 false，产品为 true）
  production: true
  alarm:
    reportTemplateId: 101
    recoverTemplateId: 102

#web端需要用得远程接口
asset:
  serverVerson: ASSET_MANAGEMENT_SERVER_1.0.0
  getCIModel: getCIModel

#是否启用内存保存企业告警等级和告警等级，需要和告警等级模块保持一致
level:
  useEnterpriseLevel: true
  serverVersion: ALARM_SERVER_LEVEL_V1.0.0
  updateEnterpriseLevelMap: updateEnterpriseLevelMap
  useAlarmLevel: false


