app:
  version: http://172.16.6.9/version.conf
  android:
    download:
      yiyijw: http://120.27.128.127:8084/release/yiyijw.apk
  code:
    yiyi: YiYi
    yiyijw: YiYiJw
    xyl: XYL
    yiyibatt: YiYiBatt
    liheng: LiHeng
file:
  version: 1.0.0.0
login:
  users:
    123456: 123456
    mystox2: 123456
#spring:
#  data:
#    mongodb:
#      host: 172.16.6.9
#      port: 27017
#      database: 3dConfiguration
mqtt:
  broker:
    host: tcp://172.16.6.142:1883
  client:
    appServer:
      topic: cntb/app/1/ywcl
      id: app1 #订阅的topic id
  sub:
    ywcl:
      topicId: cntb/ywcl/1/omc #消费的topic id
  timeout: 10000
spring:
  data:
    mongodb:
      host: 172.16.6.142
      port: 27017
      database: db_cntb_minifsu
  http:
    multipart:
      enabled: true
server:
  name: minifsu-web
  bindIp: 172.16.6.39
rpc:
  client:
    timeout: 30000
  controller:
    hostname: 172.16.6.39
    port: 18800