app:
  version: http://172.16.6.9/version.conf
  android:
    download:
      yiyijw: http://120.27.128.127:8084/release/yiyijw.apk
  code:
    yiyi: YiYi
    yiyijw: YiYiJw
    xyl: XYL
    yiyibatt: YiYiBatt
    liheng: LiHeng
file:
  version: 1.0.0.0
login:
  users:
    123456: 123456
    mystox2: 123456
#spring:
#  data:
#    mongodb:
#      host: 172.16.6.9
#      port: 27017
#      database: 3dConfiguration

spring:
  http:
    multipart:
      enabled: true
  redis:
    ## Redis数据库索引(默认为0)
    database: 2
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    host: 172.16.5.26
    port: 6379
server:
  name: minifsu-web
  bindIp: 172.16.6.240
rpc:
  client:
    timeout: 60000
  controller:
    hostname: 172.16.6.240
    port: 18800
compiler:
  server:
    url: http://172.16.5.123 #编译服务器地址
    downEngine: http://172.16.5.123 #编译服务器外网地址
    downAdapter: http://172.16.5.123 #编译服务器外网地址
    compilerPort: 14141 #适配层编译服务端口
    compilerDownloadPort: 32810 #编译服务器文件下载端口
    enginePort: 24242 #引擎服务端口
    engineDownloadPort: 32804 #引擎服务器文件下载端口
nb:
  url:
    cmcc: http://172.16.6.240:17703 #移动NB服务的WEB接口,可以为外网映射,与nb订阅关联的地址同义
    ctcc: http://