app:
  version: http://172.16.6.9/version.conf
  android:
    download:
      yiyijw: http://120.27.128.127:8084/release/yiyijw.apk
  code:
    yiyi: YiYi
    yiyijw: YiYiJw
    xyl: XYL
    yiyibatt: YiYiBatt
    liheng: LiHeng
file:
  version: 1.0.0.0
login:
  users:
    123456: 123456
    mystox2: 123456
#spring:
#  data:
#    mongodb:
#      host: 172.16.6.9
#      port: 27017
#      database: 3dConfiguration
spring:
  data:
    mongodb:
      host: 172.16.6.9
      port: 27017
      database: minifsu2
  http:
    multipart:
      enabled: true
server:
  name: minifsu-web
  bindIp: 172.16.6.50
rpc:
  client:
    timeout: 60000
  controller:
    hostname: 172.16.6.50
    port: 18800