spring:
  application:
    name: minifsu-web
  profiles:
    active: dev
logging:
  level:
   root: info
   org.apache.hadoop.util: OFF
#  config:
#    name: user-table,app-common
#    location: classpath:/,classpath:/config
server:
  port: 8081

