spring:
  profiles:
    active: dev
  application:
    name: yyds-mqtt-demo
management:
  endpoints:
    web:
      exposure:
        include: env,refresh
server:
  groupCode: GROUP_DEMO1
  name: YYDS_MQTT_DEMO
  version: 1.0.0
  port: 58000
  title: 消息框架DEMO
#  serverUri: /home #首页名
  pageRoute: proxy_mqtt_demo
  routeMark: proxy_mqtt_demo
jarResources:
  path: ./jarResources #jar包和jarRes.yml资源配置文件存放路径 默认为./jarResources
logging:
  level:
    root: info
    tech.mystox.framework.mqtt.service: info
    tech.mystox.framework.balancer: info
    tech.mystox.framework.mqtt.service.ExecutorRunner: info
    tech.mystox.framework.mqtt.service.impl.ChannelSenderImpl: info
    tech.mystox.framework.mqtt.service.impl.ChannelHandlerSub: info
    tech.mystox.framework.mqtt.service.impl.ChannelHandlerAck: info
    #    tech.mystox.framework.balancer.client.BaseLoadBalancerClient: debug
    tech.mystox.framework.register.service.ZkRegScheduler: debug
    org.apache.zookeeper: OFF
    org.apache.hadoop.util.Shell: OFF
    org.mongodb.driver.*: OFF
    org.apache.zookeeper.ZooKeeper: OFF
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20logger{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
  mqtt:
    error:
      flag: true
register:
  scanBasePackage: tech.mystox.framework
