
logging:
  level:
   root: info
   org.apache.hadoop.util.Shell: OFF

server:
  name: minifsu-tower
  bindIp: 172.16.6.39
  rpc:
    port: 18881


executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数
rpc:
  client:
    timeout: 20000