logging:
  level:
   root: info
   org.apache.hadoop.util: OFF
   org.mongodb.driver.*: OFF

mongodb:
  uri: mongodb://yyds:123456@127.0.0.1:27017/yyds

server:
  name: minifsu-business
  bindIp: 172.16.6.39
  rpc:
    port: 18830
spring:
  redis:
    ## Redis数据库索引(默认为0)
    database: 3
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 300
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    ## 连接池中的最大空闲连接
      max-idle: 100
    ## 连接池中的最小空闲连接
      min-idle: 20
    host: 172.16.5.26
    port: 6379


executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数

rpc:
  client:
    timeout: 200000
  controller:
    hostname: 172.16.6.39
    port: 18800
register:
  delay: 100