spring:
  application:
    name: yytd-mqtt-demo
  session:
    store-type: redis
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2
  kafka:
    consumer:
      group-id: siTestGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: 172.16.5.27:9093,172.16.5.27:9094,172.16.5.27:9095
kafka:
  producer:
    clientId: ${server.groupCode}_${server.name}_${server.version}_producer_${random.uuid}
    defaultTopic: topic
  completionTimeout: 3000
  consumer:
    clientId: ${server.groupCode}_${server.name}_${server.version}_consumer_${random.uuid}
    defaultTopic: topic

###########服务及消息框架相关配置#############
server:
  groupCode: GROUP_DEMO1
  name: test #服务编码
  version: 1.0.0 #服务版本
  port: 58106 #服务占用web端口
  title: 测试
jarResources:
  path: ./jarResources #可选配置 jar包和jarRes.yml资源配置文件存放路径 默认为./jarResources
register:
  scanBasePackage: tech.mystox.framework #默认配置tech.mystox.framework 如果项目的包名不一致需要手动配置
  url: zookeeper://172.16.5.62:2181,172.16.5.62:2182,172.16.5.62:2183 #开发态的服务和云管服务配置，开发态服务可以不依赖云管进行部分功能服务的开发
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.62:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  maxInflight: 1000

###########日志配置###########
logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    tech.mystox.framework.mqtt.service: DEBUG
    tech.mystox.framework.mqtt.service.ExecutorRunner: info
    org.apache.hadoop.util.Shell: OFF
    org.mongodb.driver.*: OFF
    org.apache.zookeeper.ZooKeeper: OFF
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20logger{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
management:
  endpoints:
    web:
      exposure:
        include: env,refresh
