spring:
  application:
    name: yytd-mqtt-demo
server:
  name: YYTD_MQTT_DEMO
  version: 1.0.0
  port: 52000
jarResources:
  path: ./jarResources #jar包和jarRes.yml资源配置文件存放路径 默认为./jarResources
register:
  scanBasePackage1: com.kongtrolink.framework.api
