#设置平台的IP
nbIot:
  platformIp: 180.101.147.89
  platformPort: 8743
  appId:  _Q2jM31IWIGV4LEzgYfbk7Ralega
  secret: ow9DPaEPkwUfwp_eBE0mGSCSBN0a
  packageTime:  60
  outIp: 112.17.133.189 #对外的IP 接收电信推送用
  outPort: 17702

server:
  name: GateWay-NB-Ctcc
  bindIp: 172.16.6.39
  rpc:
    port: 18883
    timeout: 6000
  port: 17702

rpc:
  client:
    timeout: 20000
  controller:
    hostname: 172.16.6.39
    port: 18800

executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数

logging:
  level:
    root: info
    org:
      apache:
        hadoop:
          util: OFF