privFunc:
  type: ROOT #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
  name: ${server.title} #权限名称 必填
  code: ROOT #权限编码 必填同级不可重复
  remark: 业务根目录 #备注 可填
#  uri: /abc/ac #uri路径 page类型填写
#  routerMark: proxy_demo #路由标记，不填写继承父节点的标记 服务节点不写默认为当前服务的路由表标记
#  pageRoute: proxy_demo #页面标记，不填写继承父节点的标记 服务节点不写默认为当前服务的路由表标记
  children:
  - type: ROOT
    name: 告警功能
    code: ALARM
    routeMark: proxy_alarm
    pageRoute: proxy_alarm
    children:
    - type: PAGE
      name: 告警等级
      code: ALARM_LEVEL
      uri: /alarmLevel
    - type: PAGE
      name: 告警列表
      code: ALARM_LIST
      uri: /alarmList
    - type: PAGE
      name: 告警周期
      code: ALARM_CYCLE
      uri: /alarmCycle
    - type: PAGE
      name: 告警投递
      code: ALARM_POST
      uri: /alarmPost
  - type: ROOT
    name: 资产功能
    code: ASSETS
    routeMark: proxy_assets
    pageRoute: proxy_assets
    children:
    - type: PAGE
      name: 告警投递
      code: MANAGE
      uri: /assetsManage_company
  - type: ROOT
    name: 报表功能
    code: REPORTS
    routeMark: proxy_reports
    pageRoute: proxy_reports
    children:
    - type: PAGE
      name: 报表任务分配
      code: SETTING
      uri: /reportSetting
    - type: PAGE
      name: 自定义报表
      code: CUSTOM
      uri: /customReport
    - type: PAGE
      name: 报表查看
      code: CUSTOM_REPORT_SHOW
      uri: /customReportShow


