privFunc:
  type: ROOT #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
  name: ${server.title} #权限名称 必填
  code: ${server.name}_${server.version} #权限编码 必填同级不可重复
  routeMark: proxy_scloud
  pageRoute: proxy_scloud
  remark: 云平台 #备注 可填
  children:
  - type: SCRIPT
    name: 服务登录验证
    code: SERVICE_LOGIN
    uri: /SDGD/static/checkLogin.js
  - type: SCRIPT
    name: 告警提醒
    code: ALARM_CONFIRM
    uri: /SDGD/static/alarmConfirm.js
  - type: PAGE
    name: 首页
    code: HOME
    uri: /SDGD/home
  - type: PAGE
    name: 综合机房
    code: SCENE
    uri: /SDGD/scene/site
  - type: PAGE
    name: 组态管理
    code: CONFIGURATION
    uri: /SDGD/configuration/manager
  - type: ROOT
    name: 数据监控
    code: DATA
    routeMark: proxy_scloud
    pageRoute: proxy_scloud
    children:
    - type: PAGE
      name: 关注数据
      code: FOCUS
      uri: /SDGD/data/focus
    - type: PAGE
      name: 实时数据
      code: SITE
      uri: /SDGD/data/site
    - type: PAGE
      name: 历史数据
      code: HISTORY
      uri: /SDGD/data/history
  - type: ROOT
    name: 告警管理
    code: ALARM
    routeMark: proxy_scloud
    pageRoute: proxy_scloud
    children:
    - type: PAGE
      name: 告警过滤
      uri: /SDGD/alarm/filter
      code: FILTER
    - type: PAGE
      name: 告警列表
      uri: /ZKSDGD/SDGD_alarmList
      code: SDGD_ALARMLIST
    - type: PAGE
      name: 关注告警
      uri: /SDGD/alarm/focus
      code: FOCUS
    - type: PAGE
      name: 告警等级
      uri: /ZKAlarm/alarmLevel
      code: ALARMLEVEL
    - type: PAGE
      name: 告警统计
      uri: /SDGD/alarm/count
      code: COUNT
    - type: PAGE
      name: 告警屏蔽
      uri: /SDGD/alarm/shield
      code: SHIELD
  - type: ROOT
    name: operation
    code: operation
    routeMark: proxy_scloud
    pageRoute: proxy_scloud
    children:
    - type: PAGE
      name: 工程管理
      code: PROJECT
      uri: /SDGD/operation/project
    - type: PAGE
      name: 告警工单
      code: WORKLIST
      uri: /SDGD/operation/workList
  - type: ROOT
    name: 系统管理
    code: SETTING
    routeMark: proxy_scloud
    pageRoute: proxy_scloud
    children:
    - type: PAGE
      name: 企业信息
      code: ENTERPRISEINFO
      uri: /ZKSDGD/enterpriseInfo
    - type: PAGE
      name: 站点资产

      code: SITEMANAGE
      uri: /ZKSDGD/siteManage
    - type: PAGE
      name: 用户管理
      code: USERMANAGE
      uri: /ZKSDGD/UserManage
    - type: PAGE
      name: 设备资产
      code: DEVICEMANAGE
      uri: /ZKSDGD/deviceManage