kafka:
  producer:
    clientId: ${server.groupCode}_${server.name}_${server.version}_producer_${random.uuid}
    defaultTopic: topic
  completionTimeout: 3000
  consumer:
    clientId: ${server.groupCode}_${server.name}_${server.version}_consumer_${random.uuid}
    defaultTopic: topic
spring:
  kafka:
    consumer:
      group-id: ${server.groupCode}
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    bootstrap-servers: 172.16.5.27:9093,172.16.5.27:9094,172.16.5.27:9095
    bootstrap-servers: ${register.kafka.url}