logging:
  level:
   root: info

server:
  name: minifsu-cntb-gw
  bindIp: 172.16.6.20
  port: 8080
  rpc:
    port: 18882


executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数

rpc:
  client:
    timeout: 20000

tower:
  service:
    hostname: 172.16.6.20
    port: 18881