spring:
  redis:
    host: 172.16.6.37
    port: 7006
    database: 5
server:
  host: 172.16.6.16
  groupCode: GROUP
  port: 59001 #服务占用web端口
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.62:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
########## mongo数据库配置 ##########
spring.data.mongodb:
  uri: mongodb://172.16.5.61:27017/scloud-product

corn:
  history: "0 * * * * ?"
