#privFunc:
#  type: ROOT #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
#  name: abc #权限名称 必填
#  code: ${server.name}_${server.version}_agc1111 #权限编码 必填同级不可重复
#  priority: 1 #权限权重
#  remark: abc #备注 可填
#  uri: /abc/ac #uri路径 page类型填写
#  routerMark: proxy_demo #路由标记，不填写继承父节点的标记
#  pageRoute: proxy_demo #页面标记，不填写继承父节点的标记
#  children:
#  - type: PAGE #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
#    name: abc #权限名称 必填
#    code: agc #权限编码 必填同级不可重复
#    uri: /abc/ac #uri路径 必填
#  - type: PAGE #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
#    name: abc #权限名称 必填
#    code: agcd #权限编码 必填同级不可重复
#    uri: /abc/ac #uri路径 必填
