spring:
  application:
    name: tower-server
  session:
    store-type: redis
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2
###########服务及消息框架相关配置#############
server:
  port: 59004 #服务占用web端口
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.26:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613

