spring:
  application:
    name: scloud-server-web
  profiles:
    active: dev,test,prod
  session:
    store-type: redis
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2
###########服务及消息框架相关配置#############
server:
  groupCode: GROUP_LIUDD_TEST
  name: SCLOUD_SERVER_WEB #服务编码
  version: 1.0.0 #服务版本
  port: 58202 #服务占用web端口
  title: 雲平台
  serverUri: /home #首页名
  pageRoute: proxy_scloud
  routeMark: proxy_scloud
jarResources:
  path: ./jarResources #可选配置 jar包和jarRes.yml资源配置文件存放路径 默认为./jarResources
register:
  scanBasePackage: com.kongtrolink.framework.scloud.api #默认配置com.kongtrolink.framework 如果项目的包名不一致需要手动配置
  url: zookeeper://172.16.5.26:2181,172.16.5.26:2182,172.16.5.26:2183 #开发态的服务和云管服务配置，开发态服务可以不依赖云管进行部分功能服务的开发


###########日志配置###########
logging:
  level:
    root: info
    com.kongtrolink.framework: info
    org.apache.hadoop.util.Shell: OFF
    org.mongodb.driver.*: OFF
    org.apache.zookeeper.ZooKeeper: OFF
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20logger{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

###########上传文件配置及文件相关配置###########
servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 100MB

file:
  savePath: D:/scloudFile/