spring:
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2
redisBusiness:
  ## Redis数据库索引(默认为0)
  database: 5
  ## 连接超时时间（毫秒）
  timeout: 60000
  ## 连接池最大连接数（使用负值表示没有限制）
  pool:
    max-active: 300
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    ## 连接池中的最大空闲连接
    max-idle: 100
    ## 连接池中的最小空闲连接
    min-idle: 20
  host: 172.16.5.26
  port: 6379
server:
  groupCode: GROUP
  name: SCLOUD_SERVER_WEB #服务编码
  #  host: 172.16.6.143
  port: 59002 #服务占用web端口
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.62:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613

########## mongo数据库配置 ##########
spring.data.mongodb:
  uri: mongodb://172.16.5.61:27017/scloud-product

executor:
  threadPool:
    corePoolSize: 10
    maxPoolSize: 1000

###########上传文件配置###########
servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 100MB

alarmModule:
  list: alarmRemoteList
  operate: alarmRemoteOperate
  updateWorkInfo: alarmRemoteUpdateWork
  level:
    getLastUse: levelRemoteLastUse
  auxilaryRemoteGet: auxilaryRemoteGet
  auxilaryRemoteDel: auxilaryRemoteDel
asset:
  getCIModel: getCIModel
deliver:
  sender: handleSender

push:
  app:
    pushKey: db1eb39511fee670d2845fdb
    pushSecret: 185e690a9858c0b580e7f0c0
    pushProduct: false
    keyName: type
    proName: workId

