logging:
  level:
    root: info
    org.apache.hadoop.util.Shell: OFF
    org.mongodb.driver.*: OFF
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20logger{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
vpn:
  osVersion: linux #vpn服务操作系统
  agent: tower #vpn代理商
  vpnList: QG7 #待检测的VPN名称列表，以‘,’分隔

server:
  name: minifsu-vpn
  bindIp: 172.16.6.20
  rpc:
    port: 18890

spring:
  redis:
    ## Redis数据库索引(默认为0)
    database: 8
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 300
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      ## 连接池中的最大空闲连接
      max-idle: 100
      ## 连接池中的最小空闲连接
      min-idle: 20
    host: 172.16.5.26
    port: 6379

executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数
