spring:
  application:
    name: gateway-common-base
  redis:
    ## Redis数据库索引(默认为0)
    database: 5
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 3
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    ## 连接池中的最大空闲连接
      max-idle: 100
    ## 连接池中的最小空闲连接
      min-idle: 20
    host: 172.16.5.60
    port: 6379
    communication:
      expired: 1200 #通讯信息默认过期时间
management:
  security:
    enabled: false
###########消息框架相关配置#############
server:
  name: GATEWAY_${gateway.businessCode}_${gateway.enterpriseCode}_FSU2 #服务编码
  version: 1.0.0 #服务版本
  port: 52002 #服务占用web端口
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.26:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
gatewayMqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.6.37:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  version: 1.0.0
gateway:
  businessCode: TOWER_SERVER_1.0.0
  enterpriseCode: YYDS
  deviceType: FSU #可选
  deviceModel: "MUU100" #可选
  regionCode: "220281" #可选
  fsuType: 38
  user: "yytd_root"
  assetReport:
    version: "1.0.0"
  alarm:
    version: "1.0.0"
  scloud:
    version: "1.0.0"