spring:
  application:
    name: gateway-common-base
  redis:
    ## Redis数据库索引(默认为0)
    database: 5
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 3
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    ## 连接池中的最大空闲连接
      max-idle: 100
    ## 连接池中的最小空闲连接
      min-idle: 20
    host: 172.16.5.60
    port: 6379
    communication:
      expired: 1200 #通讯信息默认过期时间
management:
  security:
    enabled: false
###########消息框架相关配置#############
server:
  host: 172.16.5.62
  name: GATEWAY_${gateway.businessCode}_${gateway.enterpriseCode}_FSU #服务编码
  port: 52002 #服务占用web端口
mqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.5.62:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
gatewayMqtt:
  username: root #可选配置 mqtt配置相关
  password: 123456 #可选配置 mqtt配置相关
  url: tcp://172.16.6.37:1883 #推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  version: 1.0.0