logging:
  level:
   root: info

server:
  name: minifsu-controller
  bindIp: 172.16.6.39
  rpc:
    port: 18800


executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数


rpc:
  client:
    timeout: 20000
  net-GW:
    hostname: 172.16.6.39
    port: 17700
  alarm:
    hostname: 172.16.6.39
    port: 18810
  business:
    hostname: 172.16.6.39
    port: 18830