
logging:
  level:
   root: info
   org.apache.hadoop.util.Shell: OFF

spring:
  redis:
    ## Redis数据库索引(默认为0)
    database: 3
    ## 连接超时时间（毫秒）
    timeout: 60000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 3
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    ## 连接池中的最大空闲连接
      max-idle: 100
    ## 连接池中的最小空闲连接
      min-idle: 20
    host: 172.16.5.26
    port: 6379
    communication:
      expired: 1200 #通讯信息默认过期时间

server:
  name: minifsu-controller
  bindIp: 172.16.6.39
  rpc:
    port: 18800


executor:
  threadPool:
    corePoolSize: 10 #核心执行线程数
    maxPoolSize: 1000 #最大维护线程数


rpc:
  client:
    timeout: 60000
  net-GW:
    hostname: 172.16.6.39
    port: 17700
  monitor:
    hostname: 172.16.6.39
    port: 18810
  business:
    hostname: 172.16.6.39
    port: 18830
  tower:
    hostname: 172.16.6.39
    port: 18881