privFunc:
  type: ROOT #权限类型 可选比填，类型为：PAGE-页面 ROOT-顶级节点 BUTTON-按钮 DROP_LIST-下拉列表 URL-链接
  name: ${server.title} #权限名称 必填
  code: ${server.name}_${server.version} #权限编码 必填同级不可重复
  remark: 业务根目录 #备注 可填
#  uri: /abc/ac #uri路径 page类型填写
#  routerMark: proxy_demo #路由标记，不填写继承父节点的标记 服务节点不写默认为当前服务的路由表标记
#  pageRoute: proxy_demo #页面标记，不填写继承父节点的标记 服务节点不写默认为当前服务的路由表标记
  children:
  - type: ROOT
    name: 告警功能
    code: ALARM
    routeMark: proxy_alarm
    pageRoute: proxy_alarm
    children:
    - type: PAGE
      name: 告警等级
      code: ALARM_LEVEL
      uri: /ZKAlarm/alarmLevel
    - type: PAGE
      name: 告警列表
      code: ALARM_LIST
      uri: /ZKAlarm/alarmList
    - type: PAGE
      name: 告警周期
      code: ALARM_CYCLE
      uri: /ZKAlarm/alarmCycle
    - type: PAGE
      name: 告警投递
      code: ALARM_POST
      uri: /ZKAlarm/alarmPost

