spring:
  http:
    multipart:
      enabled: true
  redis:
    host: 172.16.5.26
    port: 6379
    database: 2
server:
  groupCode: GROUP_DEMO
  host: 172.16.5.62
  port: 52202
mqtt:
  username: root
  password: 123456
  url: tcp://172.16.5.62:1883 # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
neo4j:
  username: neo4j
  password: admin
  uri: bolt://172.16.5.66:7687
logging:
  level:
    root: info
    com.kongtrolink.framework.mqtt.service.impl.MqttSenderImpl: DEBUG
    org.apache.hadoop.util.Shell: OFF
    org.mongodb.driver.*: OFF
    org.apache.zookeeper.ZooKeeper: OFF
  pattern:
    console: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20logger{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{MM-dd HH:mm:ss.SSS}){faint} %clr(${server.name} ${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([%5.5t]){faint} %clr(%-20.20{39} %5.5line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

taskInterval:
  deviceGet: 6000 #获取设备列表时间间隔，秒
appResources: #资源目录
  ciTypeIcon: AppResources/ciTypeIcon #CI类型图标文件夹，修改后需人工确认图标文件是否存放正常，该目录在应用根目录