zookeeper:
  url: 172.16.5.26:2181,172.16.5.26:2182,172.16.5.26:2183 #zookeeper集群
  sessionTimeout: 3000 ##注册超时时间应该与注册周期一致(或大于注册周期
logging:
  level:
   root: info
server:
  name: controller
  port: 7777
  bindIp: 172.16.6.242
  rpc:
    port: 8888
  tcp:
    port: 9999
register:
  cluster:
    id: test01
  periodTime: 3

balancer:
  pluginUrl:
  className:
  methodName:
  periodTime: 5
route:
  period:
    time: 10000
  expired:
    time: 10000
mqtt:
  broker:
    host: tcp://172.16.5.26:1883
  sub:
    topic: mystox
